export const SUPABASE_URL = "https://gkwsagqmipsmqjtjqffe.supabase.co";
export const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdrd3NhZ3FtaXBzbXFqdGpxZmZlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ3ODAzODksImV4cCI6MjA5MDM1NjM4OX0.2saPkwADuOOxnMBhxTcu3adBpggTJ7cdQs83F18qXPU";
